### PR TITLE
Add disclaimer!

### PR DESCRIPTION
**Pull request by gkoberger**
Heya!

We really appreciate you building this :) I added a little disclaimer, though, since we get a lot of support on our official channel about our "API not working" :)

Thanks!

### CODE REVIEW

**Comment by gkoberger** [comment]
@haroldtreen bump! we're getting a large number of support requests, and people thing this is something we've built. Thanks!

**Comment by haroldtreen** [comment]
Hey @gkoberger!

Sorry for not responding earlier. When I finished at Mobify, I was removed from the org and no longer have access to this repo.

@jansepar could we do that repo transfer magic and then you guys won't need to worry about these PRs? Or you can just merge it. Whatever works :+1:

**Comment by gkoberger** [comment]
Thanks @haroldtreen :)

**Comment by jansepar** [comment]
@haroldtreen I'll transfer this over to you.

**Comment by jansepar** [comment]
@haroldtreen I got a "haroldtreen/readmeio-sync already exists and You can only transfer a repository from an organization to yourself at this time" error message - maybe delete your fork and I'll try again?

**Comment by haroldtreen** [comment]
Deleted! :smiley:

**Comment by jansepar** [comment]
Ugh: "You can only transfer a repository from an organization to yourself at this time".

**Comment by jansepar** [comment]
Maybe we can just make your fork the official repo?

**Comment by haroldtreen** [comment]
Reforked...Anything else I'd need to do?

**Comment by jansepar** [comment]
@haroldtreen I moved it to me to move to you. Can you delete your fork?

**Comment by haroldtreen** [comment]
Yup!

**Comment by jansepar** [comment]
lol it's like we're having a real time convo - 👋Harold!

**Comment by haroldtreen** [comment]
Github is basically slack. Fork deleted :).

**Comment by jansepar** [comment]
Transfer requested!

**Comment by haroldtreen** [comment]
This has been a wonderful PR. Merging! :+1: 

Thanks @jansepar :smile:

**Pull request merged**
